name: Build Starterkit Frontend CICD

on:
  push:
    branches:
      - develop
      - staging
      - master
  workflow_dispatch:

env:
  AUTHOR: naxa
  AWS_REGION: ap-south-1

jobs:
  build:
    name: Build Static Files
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 19.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Write Environment Variables
        id: write_env
        run: |
          case "${{ github.ref }}" in
          refs/heads/develop)
          echo '
          SITE_NAME="Starter Kit -v3 (Ts)"
          BASE_URL=https://admin.naxa.com.np
          API_URL_V1=https://admin.naxa.com.np/api/v1
          ' > .env
          ;;
          refs/heads/staging)
          echo '
          SITE_NAME="Starter Kit -v3 (Ts)"
          BASE_URL=https://admin.naxa.com.np
          API_URL_V1=https://admin.naxa.com.np/api/v1
          ' > .env
          ;;
          refs/heads/master)
          echo '
          SITE_NAME="Starter Kit -v3 (Ts)"
          BASE_URL=https://admin.naxa.com.np
          API_URL_V1=https://admin.naxa.com.np/api/v1
          ' > .env
          ;;
          esac

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate build
        run: |
          yarn build

      - name: Upload Dist as Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'  }}
        with:
          name: DFIMS-${{ github.ref_name }}
          path: dist
          retention-days: 1

  deploy:
    name: Deploy Static Files
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/develop-xxx' || github.ref == 'refs/heads/staging-xxx' || github.ref == 'refs/heads/master-xxx'  }}
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get Artifacts
        uses: actions/download-artifact@v1
        with:
          path: dist
          name: DFIMS-${{ github.ref_name }}

      - name: Get VM SSH host and user
        id: get_vm_conf
        run: |
          case "${{ github.ref }}" in
          refs/heads/develop)
              export SERVER_IP=159.89.164.123
              export SERVER_USERNAME=devops
              export PROJECT_PATH=/srv/Projects/react-typescript-starterkit-v3/dist
              ;;      
              refs/heads/staging)
              export SERVER_IP=159.89.164.123
              export SERVER_USERNAME=devops
              export PROJECT_PATH=/srv/Projects/react-typescript-starterkit-v3/dist
              ;;
              refs/heads/master)
              export SERVER_IP=159.89.164.123
              export SERVER_USERNAME=devops
              export PROJECT_PATH=/srv/Projects/react-typescript-starterkit-v3/dist   
          esac
          echo "SERVER_IP=${SERVER_IP}" >> $GITHUB_OUTPUT
          echo "SERVER_USERNAME=${SERVER_USERNAME}" >> $GITHUB_OUTPUT
          echo "PROJECT_PATH=${PROJECT_PATH}" >> $GITHUB_OUTPUT

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ steps.get_vm_conf.outputs.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: copy static files
        run: |
          scp -r ./dist/* ${{ steps.get_vm_conf.outputs.SERVER_USERNAME }}@${{ steps.get_vm_conf.outputs.SERVER_IP }}:${{ steps.get_vm_conf.outputs.PROJECT_PATH }}
          echo "Build Pass"

      - name: Clean SSH keys
        run: |
          chmod 700 ~/.ssh/id_rsa
          rm -rf ~/.ssh/id_rsa